# Generated by Django 2.2 on 2020-04-26 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(null=True)),
                ('Max_value', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(null=True)),
                ('Max_value', models.FloatField(null=True)),
                ('File_Need', models.BooleanField(default=False)),
                ('Group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(null=True)),
                ('Sign', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University_Data',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.FloatField()),
                ('File', models.FileField(upload_to='')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Checked', models.BooleanField(default=False)),
                ('Criteria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Criteria')),
                ('University_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.University')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(null=True)),
                ('Max_value', models.FloatField(null=True)),
                ('Category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Category')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='Indicator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Indicator'),
        ),
    ]
