# Generated by Django 2.2 on 2020-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200429_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Max_value1',
            field=models.FloatField(null=True),
        ),
    ]
