# Generated by Django 2.2 on 2020-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_category_max_value1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(null=True)),
                ('Max_value', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='Max_value1',
        ),
    ]
