# Generated by Django 2.2 on 2020-04-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200429_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
