# Generated by Django 2.2 on 2020-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_delete_category1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='university_data',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='criteria',
            name='Formula',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='criteria',
            name='VariableName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='Logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='university',
            name='WebAddress',
            field=models.TextField(null=True),
        ),
    ]
