# Generated by Django 2.2 on 2020-05-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20200510_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Logo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='university_data',
            name='File',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
