# Generated by Django 2.2 on 2020-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20200511_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='university_data',
            name='File',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
