# Generated by Django 2.2 on 2020-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20200511_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='Max_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
