# Generated by Django 2.2 on 2020-05-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20200512_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='Formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='VariableName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
