# Generated by Django 2.2 on 2020-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20200512_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='VariableName',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
