# Generated by Django 2.2 on 2020-06-24 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_auto_20200515_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.CharField(max_length=4, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ['pk'], 'verbose_name': 'Критерий', 'verbose_name_plural': 'Критерии'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['pk'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['pk'], 'verbose_name': 'Индикатор', 'verbose_name_plural': 'Индикаторы'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['pk'], 'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
        migrations.AlterModelOptions(
            name='university_data',
            options={'ordering': ['pk'], 'verbose_name': 'Данные университета', 'verbose_name_plural': 'Данные университетов'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['pk'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='category',
            name='Max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.TextField(null=True, verbose_name='Название⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='File_Need',
            field=models.BooleanField(default=False, verbose_name='Необходимость файла'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='Formula',
            field=models.TextField(blank=True, null=True, verbose_name='⠀⠀Формула⠀⠀⠀⠀⠀'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='Group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='Indicator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Indicator', verbose_name='Индикатор'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='Max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='Name',
            field=models.TextField(null=True, verbose_name='Название⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='VariableName',
            field=models.TextField(blank=True, null=True, verbose_name='Название переменной'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Name',
            field=models.TextField(null=True, verbose_name='Название⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='Name',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='Sign',
            field=models.CharField(max_length=3, verbose_name='Знак'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Logo',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='university',
            name='WebAddress',
            field=models.TextField(null=True, verbose_name='Адрес сайта'),
        ),
        migrations.AlterField(
            model_name='university_data',
            name='Checked',
            field=models.BooleanField(default=False, verbose_name='Проверка'),
        ),
        migrations.AlterField(
            model_name='university_data',
            name='Criteria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Criteria', verbose_name='Критерий'),
        ),
        migrations.AlterField(
            model_name='university_data',
            name='Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='university_data',
            name='File',
            field=models.FileField(null=True, upload_to='files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='university_data',
            name='University_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.University', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='university_data',
            name='Value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='PhoneNumber',
            field=models.TextField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Position',
            field=models.TextField(blank=True, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='University_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.University', verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='category',
            name='Year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Year', verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='Year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Year', verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='group',
            name='Year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Year', verbose_name='Год'),
        ),
    ]
