# Generated by Django 2.2 on 2020-06-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_auto_20200624_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_data',
            name='Year_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Year', verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='File_Need',
            field=models.BooleanField(default=False, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='Formula',
            field=models.TextField(blank=True, null=True, verbose_name='⠀⠀⠀⠀⠀Формула⠀⠀⠀⠀⠀'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='Max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Макс знач'),
        ),
    ]
