# Generated by Django 2.2 on 2020-07-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_auto_20200624_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_data',
            name='Year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Year', verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='Sub_Data',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.BooleanField(null=True, verbose_name='Значение')),
                ('Criteria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Criteria', verbose_name='Критерий')),
                ('University_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.University', verbose_name='Университет')),
            ],
        ),
    ]
