# Generated by Django 2.2 on 2020-07-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_auto_20200702_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Criteria',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(verbose_name='Название')),
                ('Max_value', models.FloatField(null=True, verbose_name='Значение')),
                ('Criteria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Criteria', verbose_name='Критерий')),
            ],
        ),
    ]
