# Generated by Django 2.2 on 2020-07-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_auto_20200702_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_data',
            name='Year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Year', verbose_name='Год'),
        ),
    ]
