# Generated by Django 2.2 on 2020-07-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_sub_data_year_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_data',
            name='Criteria_id',
        ),
        migrations.AddField(
            model_name='sub_data',
            name='Sub_criteria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Sub_Criteria', verbose_name='Под Критерий'),
        ),
    ]
