# Generated by Django 2.2 on 2020-07-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_auto_20200702_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_data',
            name='Sub_criteria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_data', to='form.Sub_Criteria', verbose_name='Под Критерий'),
        ),
    ]
