# Generated by Django 2.2 on 2020-11-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_auto_20200703_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_form',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('raddate', models.TextField()),
                ('job', models.TextField()),
                ('position', models.TextField()),
                ('salary', models.TextField()),
                ('continue_study', models.TextField()),
                ('name_university', models.TextField()),
                ('level_of_education', models.IntegerField()),
                ('major', models.TextField()),
                ('study_terms', models.TextField()),
                ('army_terms', models.TextField()),
                ('maternity_leave_term', models.IntegerField()),
                ('teachers_knowledge', models.IntegerField()),
                ('teachers_explaining', models.IntegerField()),
                ('masters_knowledge', models.IntegerField()),
                ('masters_explaining', models.IntegerField()),
                ('curators_work', models.IntegerField()),
                ('ready', models.IntegerField()),
                ('skills', models.IntegerField()),
                ('connection', models.IntegerField()),
                ('oriented', models.IntegerField()),
                ('help', models.IntegerField()),
                ('professional_skills', models.IntegerField()),
                ('ability_improve', models.IntegerField()),
                ('easy_adaptation', models.IntegerField()),
                ('organization', models.IntegerField()),
                ('talking_skills', models.IntegerField()),
                ('responsibility', models.IntegerField()),
                ('theory_using', models.IntegerField()),
                ('repeat_study', models.CharField(max_length=10)),
                ('same_major', models.CharField(max_length=10)),
                ('satisfaction', models.CharField(max_length=10)),
                ('start_working', models.IntegerField()),
                ('matching', models.IntegerField()),
                ('lack', models.IntegerField()),
                ('vacancy_lack', models.IntegerField()),
                ('low_salary', models.IntegerField()),
                ('no_money', models.IntegerField()),
                ('work_search', models.IntegerField()),
                ('success_search', models.IntegerField()),
                ('new_idea', models.IntegerField()),
                ('adapt', models.IntegerField()),
                ('time_man', models.IntegerField()),
                ('talking_skills_1', models.IntegerField()),
                ('responsibility_1', models.IntegerField()),
                ('solving_1', models.IntegerField()),
                ('using_1', models.IntegerField()),
                ('skills_using_1', models.IntegerField()),
                ('why_1', models.IntegerField()),
                ('after_1', models.IntegerField()),
                ('where_1', models.IntegerField()),
                ('University_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.University', verbose_name='Университет')),
            ],
        ),
    ]
