# Generated by Django 2.2 on 2020-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_student_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_form',
            name='continue_study',
        ),
        migrations.AlterField(
            model_name='student_form',
            name='maternity_leave_term',
            field=models.TextField(),
        ),
    ]
