# Generated by Django 2.2 on 2020-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_auto_20201205_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_form',
            name='solving',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
