# Generated by Django 2.2 on 2020-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_student_form_solving'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_form',
            name='networking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
