# Generated by Django 2.2 on 2020-12-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_student_form_own_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_form',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('raddate', models.TextField()),
                ('major', models.TextField()),
                ('job', models.TextField()),
                ('position', models.TextField()),
                ('salary', models.TextField()),
                ('synthesis', models.IntegerField()),
                ('using', models.IntegerField()),
                ('time_management', models.IntegerField()),
                ('base_knowledge', models.IntegerField()),
                ('preparing', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('lang_knowledge', models.IntegerField()),
                ('comp_work', models.IntegerField()),
                ('exploring', models.IntegerField()),
                ('studying', models.IntegerField()),
                ('inf_work', models.IntegerField()),
                ('criticism', models.IntegerField()),
                ('adapt', models.IntegerField()),
                ('new_ideas', models.IntegerField()),
                ('solving', models.IntegerField()),
                ('decision', models.IntegerField()),
                ('team_work', models.IntegerField()),
                ('personal', models.IntegerField()),
                ('leadership', models.IntegerField()),
                ('team_disc_work', models.IntegerField()),
                ('nospec_work', models.IntegerField()),
                ('internat_work', models.IntegerField()),
                ('indep_work', models.IntegerField()),
                ('development', models.IntegerField()),
                ('initiate', models.IntegerField()),
                ('ethics', models.IntegerField()),
                ('caring', models.IntegerField()),
                ('ambition', models.IntegerField()),
                ('University_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.University', verbose_name='Университет')),
                ('Year_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Year', verbose_name='Год')),
            ],
        ),
    ]
