# Generated by Django 2.2 on 2021-01-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_dig_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='dig_form',
            name='Year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Year', verbose_name='Год'),
        ),
    ]
