# Generated by Django 2.2 on 2021-01-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_dig_form_year_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_form',
            old_name='age',
            new_name='e_number',
        ),
        migrations.RenameField(
            model_name='emp_form',
            old_name='fio',
            new_name='org_name',
        ),
        migrations.RemoveField(
            model_name='emp_form',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='emp_form',
            name='job',
        ),
        migrations.RemoveField(
            model_name='emp_form',
            name='raddate',
        ),
    ]
