# Generated by Django 2.2 on 2021-01-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_auto_20210114_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='emp_form',
            name='major',
        ),
        migrations.AddField(
            model_name='emp_form',
            name='Major_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Major', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='student_form',
            name='Major_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.Major', verbose_name='Специальность'),
        ),
    ]
