# Generated by Django 2.2 on 2021-01-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_auto_20210114_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_form',
            name='major',
        ),
    ]
