# Generated by Django 2.2 on 2021-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_remove_student_form_major'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ['pk'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AddField(
            model_name='student_form',
            name='major',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='major',
            name='Name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
