# Generated by Django 2.2 on 2021-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_remove_student_form_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_form',
            name='major',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
